apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - digitalsoba.com
    secretName: digitalsoba-com-tls
  rules:
  - host: digitalsoba.com
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
