apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: blog
  environment: production

namespace: production

bases:
- ../../base

replicas:
- name: blog
  count: 2

patchesStrategicMerge:
- ingress.yml
- service.yml
