apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: blog
  environment: production

namespace: production

images:
- name: ghcr.io/digitalsoba/digitalsoba.com
  newTag: latest


replicas:
- count: 2
  name: blog

patchesStrategicMerge:
- ingress.yml
- service.yml

resources:
- ../../base
