apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
spec:
  rules:
    - host: localhost
      http:
        paths:
        - backend:
            serviceName: blog
            servicePort: 80
