apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
spec:
  rules:
    - host: localhost
      http:
        paths:
        - paths: /blog
          pathType: Prefix
          backend:
            service:
              name: blog
              port: 
                number: 80
