
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: blog
  environment: dev

resources:
- deployment.yml
- ingress.yml
- service.yml

images:
- name: ghcr.io/digitalsoba/digitalsoba.com
  newTag: latest
