name: Build and Deploy

on:
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get sha
        id: get-sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short=9 HEAD)"  
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} 
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: digitalsoba/digitalsoba.com:${{ steps.get-sha.outputs.sha_short }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

