name: ci

on:
  pull_request:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: digitalsoba/digitalsoba.com:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

