apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: blog
  environment: staging

namespace: staging

images:
- name: ghcr.io/digitalsoba/digitalsoba.com
  newTag: latest

patchesStrategicMerge:
- ingress.yml
- service.yml

resources:
- ../../base
